
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password:

development:
  <<: *default
  database: task-manager-api_development

test:
  <<: *default
  database: task-manager-api_test

production:
  <<: *default
  database: task-manager-api_production
  username: task-manager-api
  password: <%= ENV['TASK-MANAGER-API_DATABASE_PASSWORD'] %>
